### PR TITLE
Floating topbar + Settings widget

### PR DESCRIPTION
**Pull request by Frawstcrabs**
yet another step closer to completely ripping off 4chan X

- Topbar is now fixed to top of page
- Widget dropdown removed, replaced with buttons on the right of the topbar
- Debounced search widget (please for the love of god use debounces)
- Default baseUrl for board and thread page is now the currently used URL
  - Reason for this is that the time travel widget would glitch out and break on invalid boards/threads (e.g. if you time travel to before a board was created) because baseUrl is undefined, so you couldn't use the widget to time travel back to the present and would have to edit the URL or go to the front page to make the site work again
- Pages auto-scroll to top on content change
  - Feels more natural to do so, keeps up the illusion that each thread/board/whatever is a separate page and not just the same page with the data swapped out
- Added basic settings widget
  - Now you can change the subgraph/IPFS endpoints and completely break the site
  - Also moved the post filter settings into it
- Converted FAQ, Rules and Abuse pages into overlays

### CODE REVIEW

**Comment by Frawstcrabs** [comment]
Hey, FYI, there's a bit of an issue when it comes to settings: The settings that are saved for some people (at least those who visited the site before the new subgraph) are actually invalid, e.g. they still point to the old subgraph, and a now invalid IPFS endpoint link. Turns out pretty much nothing besides the EULA and the filter settings was actually reading from local storage, everything else was just going straight to DefaultSettings. That's now fixed, but it also means these issues are gonna start to matter if this gets merged. We should definitely put out a notice to update these settings as soon as you refresh to load the latest version, which is just to add "-0" to the end of the subgraph endpoint link, and to remove the "/add" from the end of the IPFS endpoint link.

**Comment by Frawstcrabs** [comment]
Also this PR sorta turned into floating topbar + settings, but fuck it, I was gonna do it anyway.

**Comment by Frawstcrabs** [comment]
Wait hold on, I need to fix an issue regarding the endpoint used in the apollo client

**Comment by Frawstcrabs** [comment]
Now it should be all good. Just need to get users with issues to reset their endpoints to default and everything should work.

**Comment by Frawstcrabs** [comment]
Actually, now that I think about it, does it actually make sense to allow people to change the subgraph endpoint? Basically the only people having that option benefits is people who would create their own derivative subgraph and use that instead of the production one (in other words, us), but everyone else would probably just want to have the subgraph update with the frontend and avoid having to bother changing it. Maybe it would be better to only use the one in DefaultSettings and skip the one in local storage entirely, since if you can go through the effort to set up a local subgraph, you can go through the effort to set up a local frontend server too.

Then again, you could also argue that having to update the subgraph endpoint is what you get for using a site in alpha (especially when you can just go into settings and hit "Reset to default" to fix it), and that having to change the endpoint due to breaking changes is a rare occurrence anyway, so maybe it's worth it for the versatility?

**Comment by opatdchan** [comment]
Sorry for disappearing! I'll take a look at it later today. Hopefully.

>Actually, now that I think about it, does it actually make sense to allow people to change the subgraph endpoint? Basically the only people having that option benefits is people who would create their own derivative subgraph and use that instead of the production one (in other words, us), but everyone else would probably just want to have the subgraph update with the frontend and avoid having to bother changing it. Maybe it would be better to only use the one in DefaultSettings and skip the one in local storage entirely, since if you can go through the effort to set up a local subgraph, you can go through the effort to set up a local frontend server too.
The fact that people can create derivative subgraphs is reason enough to let users customize the setting. There is no practical use just yet, but there is no reason why we shouldn't let people do it without having to build a custom client.

To avoid needing people to manually reset the settings, I'd rather just change the localstorage name so that we don't load the old version.

**Comment by Frawstcrabs** [comment]
> The fact that people can create derivative subgraphs is reason enough to let users customize the setting. There is no practical use just yet, but there is no reason why we shouldn't let people do it without having to build a custom client.
> 
> To avoid needing people to manually reset the settings, I'd rather just change the localstorage name so that we don't load the old version.

To be clear, I'm not personally against adding it at all; my concern is with the fact that even if we do change the localstorage name this time around, we'll still come across this issue if we change the subgraph again down the line. Since it'll become a locally saved setting and not just something that's part of the client, the user will have to remember to change to the new endpoint whenever the subgraph is updated instead of just refreshing the page as usual, making things ever-so-slightly less retard-proof.

I might just be over-reacting though, since the client (for some reason) can only get the board list on the old subgraph and nothing else, but that might just be an issue with this subgraph specifically and not for future ones. It'll also be a pretty rare issue since we're not doing much with the subgraph anyway, but it's something worth noting. Maybe a pre-warning is good enough?

**Comment by opatdchan** [comment]
Good points. 
I'd rather keep it as retard-proof as possible, users should not be concerned about it. It probably makes sense to hardcode the endpoints for the time being, especially before we migrate the subgraph to mainnet, while we can figure out a proper solution. 

On November 2, 2021 6:15:00 PM GMT+01:00, Frawstcrabs ***@***.***> wrote:
>> The fact that people can create derivative subgraphs is reason enough
>to let users customize the setting. There is no practical use just yet,
>but there is no reason why we shouldn't let people do it without having
>to build a custom client.
>> 
>> To avoid needing people to manually reset the settings, I'd rather
>just change the localstorage name so that we don't load the old
>version.
>
>To be clear, I'm not personally against adding it at all; my concern is
>with the fact that even if we do change the localstorage name this time
>around, we'll still come across this issue if we change the subgraph
>again down the line. Since it'll become a locally saved setting and not
>just something that's part of the client, the user will have to
>remember to change to the new endpoint whenever the subgraph is updated
>instead of just refreshing the page as usual, making things
>ever-so-slightly less retard-proof.
>
>I might just be over-reacting though, since the client (for some
>reason) can only get the board list on the old subgraph and nothing
>else, but that might just be an issue with this subgraph specifically
>and not for future ones. It'll also be a pretty rare issue since we're
>not doing much with the subgraph anyway, but it's something worth
>noting. Maybe a pre-warning is good enough?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dchan-network/dchan-client/pull/23#issuecomment-957959542

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Frawstcrabs** [comment]
I'll just comment out the endpoint settings in the widget and use the ones in DefaultSettings for now. I should also see if I can make it so that the latest endpoints are written to the user's localstorage on page load, so that it's all up-to-date when we re-enable it.

**Comment by opatdchan** [comment]
Excellent work as always. Thank you! 😃

**Pull request merged**
