### PR TITLE
Refactor post parser

### PR DESCRIPTION
**Pull request by Frawstcrabs**
- Post content formatting completely overhauled
  - Uses a custom parser (recursive things like nested [spoiler] tags now work)
  - Rendered using React elements instead of via HTML and regex
  - Parjs added as a dependency
- Hovering over a post reference now highlights the post in the thread
- (You) support

### CODE REVIEW

**Comment by Frawstcrabs** [comment]
A couple sidenotes:
- Is it me, or is the formatting of backlinks identical to that of normal posts? I couldn't see a single difference when I was reading the code, so I just removed it outright. Backlinks are now handled on the PostReference element level, so there's no longer a need for whatever hack they served anyway.
- How come Post objects coming from a Thread page still have their `thread` attribute set to null?

**Comment by opatdchan** [comment]
Good work. Thank you for your effort, very appreciated. 
Once ready I'll give it a go as soon as I manage to get my hands on my pc (I'm out of commission for a while, possibly a week) or just directly merge it if you tested it already. Same goes for the other PR.
If something makes no sense it's probably the result of  rushed development, don't try to reason too much about it 😄 both points are possibly leftovers of old implementations. Feel free to rip out anything that doesn't make sense. 

On September 19, 2021 1:24:32 AM GMT+02:00, Frawstcrabs ***@***.***> wrote:
>A couple sidenotes:
>- Is it me, or is the formatting of backlinks identical to that of
>normal posts? I couldn't see a single difference when I was reading the
>code, so I just removed it outright. Backlinks are now handled on the
>PostReference element level, so there's no longer a need for whatever
>hack they served anyway.
>- How come Post objects coming from a Thread page still have their
>`thread` attribute set to null?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dchan-network/dchan-client/pull/8#issuecomment-922387898

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Frawstcrabs** [comment]
From the testing I've done so far, this should be ready to merge.

**Comment by Frawstcrabs** [comment]
bump

**Comment by opatdchan** [comment]
Finally managed to get a hold of a laptop. Tried this out, looks good, thank you! Post highlight on hover is really cool, and the parser was a much needed change. I'll try the other PR out now, should I merge the other one and then this one?

**Comment by opatdchan** [comment]
[Post highlight had to be disabled](https://github.com/dchan-network/dchan-client/commit/45337a21a558ee67969656f859a4d6edcdd98341#diff-e53731d64e59c6efcd5ecbdbad9fe29bb8394d04809a181c3ae98def3c10a407) because if I click on a link I also need to leave the link, unhighlighting it.

**Pull request merged**
