### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by Frawstcrabs**
- PostBody now caches parser result
- Clicking on a post ref now goes through POST_FOCUS instead of a link, saves a few renders of Thread
- Fixed post refs not being able to find their post
- Fixed moving away from a post ref dehighlighting a focused post

To give you an idea of how important caching the parser result is, opening https://dchan.network/#/0xaef23b, a thread with 61 posts, would cause about 2000 PostBody renders. Caching this alone brought it down to about 150 (2.5 renders per post, the extra due to backlinking and rendering Thread twice). I fucked up.

The other changes whittle this down further where possible to minimise re-renders.

### CODE REVIEW

**Comment by Frawstcrabs** [comment]
One of the things I noticed when it came to post focus lag is that, when I commented out the line which writes to the browser history, the focus is done instantly, but when I leave it, the page re-renders the entire thread, and *then* focuses the post. It's probably then worth noting that a call to `history.push` or `history.replace` will cause a full-page re-render, whether you need it to or not.

Thankfully, there's a function `React.memo` which you can wrap a functional component around, which makes it so it only gets re-rendered when its props change (state still updates it), and Post/PostBody fit the bill for it perfectly. Wrapping those two components means a post focus only reloads the top-level thread component and all of the inner Post components are untouched, which pretty much eliminates the lag.

**Comment by Frawstcrabs** [comment]
Is it worth considering query optimisations too? I had at least one idea for that, where we make a new Post fragment that excludes thread/board data for use in the THREAD_GET query, since otherwise each Post is just getting redundant thread info for no reason. You can just fill in the gap by assigning the Thread/Board object to each individual post. I'm sure there are other ways to optimise queries as well.

**Comment by opatdchan** [comment]
It seems like premature optimization IMO. I'm aware there is a lot of redundant data being returned, but unless we are able to shave hundreds of kilobytes per query or more there is no need just yet. It would only benefit client performance on low speed/quality networks and we wouldn't save costs on queries anyway.
Will certainly need to be done sometime down the line, although maybe it's a simple enough change to do now? You probably have a better idea than me at this point 😄

On September 26, 2021 2:24:41 AM GMT+02:00, Frawstcrabs ***@***.***> wrote:
>Is it worth considering query optimisations too? I had at least one
>idea for that, where we make a new Post fragment that excludes
>thread/board data for use in the THREAD_GET query, since otherwise each
>Post is just getting redundant thread info for no reason. You can just
>fill in the gap by assigning the Thread/Board object to each individual
>post. I'm sure there are other ways to optimise queries as well.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dchan-network/dchan-client/pull/10#issuecomment-927203197

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Frawstcrabs** [comment]
Honestly the main reason I wanna do it is to have it so `post.thread` points to the full thread object when it's available, since a lot of the time things get passed both the post and the full thread separately. Being able to cut down on query responses is just a nice bonus. Maybe I'm just bikeshedding though, I dunno.

**Pull request merged**
