### PR TITLE
UI tweaks

### PR DESCRIPTION
**Pull request by Frawstcrabs**
A shitload more stuff to make the UI feel a bit more like 4chan/4chan X.
- Changed post text layout, now it goes next to and under the post image
- Added a bit more padding around the post contents to make it a bit easier to read
- Fixed the filename and hash causing the post box to go outside the window on mobile (now it just gets truncated with an ellipsis)
- Generally made posts fit better on mobile
- References are now 4chan red
- Dates are now in the same format as 4chan (relative time was moved to the hover-over title)
- Replies in catalog threads are now capped to 3 lines in height

PC view: https://i.imgur.com/m7AHnoC.png
Mobile view: https://i.imgur.com/B1K53oF.png

There is one bug that I can't seem to figure out though, where some threads, despite all of the page contents being inside the window, will just have the right-side dropdown go way off to the right and you need to scroll to see it. I can't see anything causing this behaviour, but it only affects some threads (most notably http://dchan.network/#/dchan/0x16bd49/0xff5f24/1631600919), and only on mobile. It's also worth pointing out this bug occurs even on the main site, yet somehow my changes have made the problem worse. Maybe it's fine though?

I'm open to suggestions on which of these design changes to change or get rid of, but this is what I think would work well.

### CODE REVIEW

**Comment by opatdchan** [comment]
Sorry, I pushed directly to master before realizing it would conflict with this PR. I need to get used to not working alone anymore.
I have changed some things, like how image fitting is handled, IDK what you've done here but feel free to overwrite if it conflicts with your solution.

**Comment by Frawstcrabs** [comment]
I figured out the weird bug on mobile where some pages would extend way out to the right for no reason.
It's because the summary section of each post is only made invisible when not shown, but for some reason it still takes up the same amount of space, and long posts would cause the comment part of the summary to extend way out to the right. If you collapse a post on the main site, you'll see what I mean.
I fixed it by simply removing the comment part altogether (I think it looks cleaner without it), but another fix is to just have that part be truncated instead.

**Comment by Frawstcrabs** [comment]
I am doing way too much in a single PR, fuck this. I'm getting weird performance issues now and I'm too deep in my commits to figure out why. I'm just gonna redo this in separate PRs.

**Comment by opatdchan** [comment]
image

**Pull request closed without merging**
